# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  -  stage: Testing
     jobs:
       - job: myjob
         steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                echo 'Hello my team'                
                echo 'Hello world'
          
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'
  