
spring:
  kafka:
    producer:      
      bootstrap-servers:localhost:9191
			key-serializer:org.apache.kafka.common.serialization.StringSerializer  
      value-serializer:org.apache.kafka.support.serialier.JsonSerializer
        